/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javakahootz;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.WindowConstants;

/**
 *
 * @author naimm
 */
public class AnswerQuestion extends javax.swing.JDialog {

    public final int index;
    public final Question question;
    public boolean is_correct = false;

    /**
     * Creates new form AnswerQuestion
     */
    public AnswerQuestion(java.awt.Frame parent, boolean modal, int index, Question question) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.index = index;
        this.question = question;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitle = new javax.swing.JLabel();
        BtnCreateQuiz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtQuestion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AnsD = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        AnsC = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        AnsB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        AnsA = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblTitle.setText("Question #");

        BtnCreateQuiz.setBackground(new java.awt.Color(102, 102, 255));
        BtnCreateQuiz.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCreateQuiz.setForeground(new java.awt.Color(255, 255, 255));
        BtnCreateQuiz.setText("Next");
        BtnCreateQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateQuizActionPerformed(evt);
            }
        });

        jScrollPane1.setEnabled(false);

        TxtQuestion.setEditable(false);
        TxtQuestion.setColumns(20);
        TxtQuestion.setRows(5);
        jScrollPane1.setViewportView(TxtQuestion);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("D");

        AnsD.setText("Answer D");
        AnsD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsDActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("C");

        AnsC.setText("Answer C");
        AnsC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsCActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("B");

        AnsB.setText("Answer B");
        AnsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A");

        AnsA.setText("Answer A");
        AnsA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsAActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pick Answer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnsA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnsB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnsC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnsD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnsA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnsB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnsC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnsD)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnCreateQuiz))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCreateQuiz)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateQuizActionPerformed
        try {
            // check if there is empty field
            if (!AnsA.isSelected() && !AnsB.isSelected() && !AnsC.isSelected() && !AnsD.isSelected()) {
                throw new Exception("Please choose at least one answer!");
            }

            ArrayList<String> pos = new ArrayList<String>(Arrays.asList("Correct!", "Wow! Correct Answer!", "Good Job!", "Correct Answer! EZPZ"));
            ArrayList<String> neg = new ArrayList<String>(Arrays.asList("Awwww your answer is incorrect :(", "Incorrect! Better luck next time.", "Incorrect!", "Wrong answer!"));

            if (AnsA.isSelected()) {
                System.out.println(this.question.answer_list.get(0).is_correct);
                this.is_correct = this.question.answer_list.get(0).is_correct;
            } else if (AnsB.isSelected()) {
                System.out.println(this.question.answer_list.get(1).is_correct);
                this.is_correct = this.question.answer_list.get(1).is_correct;
            } else if (AnsC.isSelected()) {
                System.out.println(this.question.answer_list.get(2).is_correct);
                this.is_correct = this.question.answer_list.get(2).is_correct;
            } else if (AnsD.isSelected()) {
                System.out.println(this.question.answer_list.get(3).is_correct);
                this.is_correct = this.question.answer_list.get(3).is_correct;
            }

            if (this.is_correct) {
                JOptionPane.showMessageDialog(null, pos.get((int) (Math.random() * pos.size())));
            } else {
                JOptionPane.showMessageDialog(null, neg.get((int) (Math.random() * neg.size())));
            }

            setVisible(false);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BtnCreateQuizActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LblTitle.setText("Question No. " + (this.index + 1));

        TxtQuestion.setText(this.question.title);

        ArrayList<JRadioButton> all_answer = new ArrayList<JRadioButton>(Arrays.asList(AnsA, AnsB, AnsC, AnsD));

        for (int i = 0; i < all_answer.size(); i++) {
            Answer answer = this.question.answer_list.get(i);

            all_answer.get(i).setText(answer.title);
        }
    }//GEN-LAST:event_formWindowOpened

    private void AnsAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsAActionPerformed
        AnsA.setSelected(true);
        AnsB.setSelected(false);
        AnsC.setSelected(false);
        AnsD.setSelected(false);
    }//GEN-LAST:event_AnsAActionPerformed

    private void AnsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsBActionPerformed
        AnsA.setSelected(false);
        AnsB.setSelected(true);
        AnsC.setSelected(false);
        AnsD.setSelected(false);
    }//GEN-LAST:event_AnsBActionPerformed

    private void AnsCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsCActionPerformed
        AnsA.setSelected(false);
        AnsB.setSelected(false);
        AnsC.setSelected(true);
        AnsD.setSelected(false);
    }//GEN-LAST:event_AnsCActionPerformed

    private void AnsDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsDActionPerformed
        AnsA.setSelected(false);
        AnsB.setSelected(false);
        AnsC.setSelected(false);
        AnsD.setSelected(true);
    }//GEN-LAST:event_AnsDActionPerformed

    public boolean showDialog() {
        setVisible(true);

        return this.is_correct;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AnsA;
    private javax.swing.JRadioButton AnsB;
    private javax.swing.JRadioButton AnsC;
    private javax.swing.JRadioButton AnsD;
    private javax.swing.JButton BtnCreateQuiz;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JTextArea TxtQuestion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
