/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javakahootz;

import java.awt.Color;
import java.io.FileReader;
import java.io.Reader;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author naimm
 */
public class CreateQuizMenu extends javax.swing.JFrame {

    /**
     * Creates new form CreateQuizMenu
     */
    public CreateQuizMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        BtnCreateQuiz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblQuiz = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Create Quiz Menu");

        BtnBack.setBackground(new ThemeColors().dark);
        BtnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack.setText("Back");
        BtnBack.setToolTipText("Back to Main Menu");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnCreateQuiz.setBackground(new ThemeColors().primary);
        BtnCreateQuiz.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnCreateQuiz.setForeground(new java.awt.Color(255, 255, 255));
        BtnCreateQuiz.setText("Create New Quiz");
        BtnCreateQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateQuizActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("View your created quiz");

        TblQuiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quiz Title", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblQuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblQuizMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblQuiz);
        if (TblQuiz.getColumnModel().getColumnCount() > 0) {
            TblQuiz.getColumnModel().getColumn(1).setResizable(false);
            TblQuiz.getColumnModel().getColumn(2).setResizable(false);
            TblQuiz.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCreateQuiz))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCreateQuiz)
                    .addComponent(BtnBack))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            JSONParser parser = new JSONParser();
            Reader reader = new FileReader("tb_quiz.txt");
            JSONArray arr = (JSONArray) parser.parse(reader);

            DefaultTableModel model = (DefaultTableModel) TblQuiz.getModel();

            for (int i = 0; i < arr.size(); i++) {
                Quiz quiz = new Quiz((JSONObject) arr.get(i));
                System.out.println("\n" + (i + 1) + ". " + quiz.title);
                model.addRow(new Object[]{quiz.title, "Leaderboard", "Edit", "Delete"});
            }

            // styling edit and delete cell
            TblQuiz.getColumnModel().getColumn(1).setCellRenderer(new ColumnColorRenderer(new ThemeColors().info, Color.WHITE));
            TblQuiz.getColumnModel().getColumn(2).setCellRenderer(new ColumnColorRenderer(new ThemeColors().warning, Color.WHITE));
            TblQuiz.getColumnModel().getColumn(3).setCellRenderer(new ColumnColorRenderer(new ThemeColors().danger, Color.WHITE));
            TblQuiz.getColumnModel().getColumn(2).setPreferredWidth(3);
            TblQuiz.getColumnModel().getColumn(3).setPreferredWidth(3);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void TblQuizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblQuizMouseClicked
        int row = TblQuiz.rowAtPoint(evt.getPoint());
        int col = TblQuiz.columnAtPoint(evt.getPoint());

        if (row >= 0 && col >= 0) {
            if (col == 1) {
                System.out.println("Leaderboard ");
            } else if (col == 2) {
                System.out.println("Editing ");

            } else if (col == 3) {
                System.out.println("Deleting ");
            }
        }
    }//GEN-LAST:event_TblQuizMouseClicked

    private void BtnCreateQuizActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnCreateQuizActionPerformed
        this.dispose();

        new CreateQuizSettings().setVisible(true);
    }// GEN-LAST:event_BtnCreateQuizActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnBackActionPerformed
        this.dispose();

        new MainMenu().setVisible(true);
    }// GEN-LAST:event_BtnBackActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BtnEditActionPerformed

    private void BtnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnEdit1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BtnEdit1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnCreateQuiz;
    private javax.swing.JTable TblQuiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
