/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javakahootz;

import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author naimm
 */
public class UserEdit extends javax.swing.JFrame {

    User user;

    /**
     * Creates new form UserEdit
     *
     * @param user
     */
    public UserEdit(User user) {
        initComponents();
        this.user = user;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        TxtPassword2 = new javax.swing.JPasswordField();
        BtnConfirmSignUp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnDiscard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Re-enter Password");

        BtnConfirmSignUp.setBackground(new ThemeColors().success);
        BtnConfirmSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnConfirmSignUp.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmSignUp.setText("Confirm");
        BtnConfirmSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmSignUpActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Edit user details. To confirm edit click confirm.");

        BtnDiscard.setBackground(new ThemeColors().danger);
        BtnDiscard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDiscard.setForeground(new java.awt.Color(255, 255, 255));
        BtnDiscard.setText("Discard");
        BtnDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDiscardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BtnDiscard)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnConfirmSignUp))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtPassword2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TxtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConfirmSignUp)
                    .addComponent(BtnDiscard))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmSignUpActionPerformed
        String name = TxtUsername.getText();
        String pwd = new String(TxtPassword.getPassword());
        String pwd2 = new String(TxtPassword2.getPassword());

        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to confirm this changes?");

        if (reply == JOptionPane.YES_OPTION) {
            try {
                // check if there is empty field
                if (name.equals("") || pwd.equals("") || pwd2.equals("")) {
                    throw new Exception("Please enter all field.");
                }

                // check if password and re-enter password isn't the same
                if (!pwd.equals(pwd2)) {
                    throw new Exception("Password and Re-enter password is not same.");
                }

                // check if username already taken
                if (isUsernameDuplicateExcept(name, this.user.username)) {
                    throw new Exception("Username taken. Please enter different username.");
                }

                Users users = new Users();
                JSONArray arr = users.getJSONArray();
                int selected_user_index = 0;

                for (int i = 0; i < users.size(); i++) {
                    User checking_user = users.getUserByIndex(i);

                    if (checking_user.username.equals(this.user.username)) {
                        selected_user_index = i;
                    }
                }
                arr.remove(selected_user_index);

                JSONObject userJSON = new JSONObject();
                userJSON.put("username", name);
                userJSON.put("password", pwd);

                arr.add(userJSON);

                // clear text file
                FileWriter fwOb = new FileWriter("tb_user.txt", false);
                PrintWriter pwOb = new PrintWriter(fwOb, false);
                pwOb.flush();
                pwOb.close();
                fwOb.close();

                // write back all of users with new user added
                FileWriter writer = new FileWriter("tb_user.txt", true);
                writer.write(arr.toJSONString());

                writer.close();

                // close window
                this.dispose();
                new ManageUser().setVisible(true);
                JOptionPane.showMessageDialog(null, "Success editing user " + this.user.username);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_BtnConfirmSignUpActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TxtUsername.setText(this.user.username);
        TxtPassword.setText(this.user.password);
        TxtPassword2.setText(this.user.password);
    }//GEN-LAST:event_formWindowOpened

    private void BtnDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDiscardActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to discard all changes?");

        if (reply == JOptionPane.YES_OPTION) {
            this.dispose();
            new ManageUser().setVisible(true);
        }
    }//GEN-LAST:event_BtnDiscardActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmSignUp;
    private javax.swing.JButton BtnDiscard;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JPasswordField TxtPassword2;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    public static boolean isUsernameDuplicateExcept(String check_username, String original_username) {
        try {
            JSONParser parser = new JSONParser();

            Users users = new Users();

            for (int i = 0; i < users.size(); i++) {
                User user = users.get(i);

                if (check_username.equals(user.username) && !check_username.equals(original_username)) {
                    return true;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return false;
    }
}
